<?php

use Illuminate\Support\Facades\Route;

// This fallback route ensures that any non-API request is handed over to the Vue SPA.
// It reads the index.html generated by Vite in the 'public/build' directory.
Route::fallback(function () {
    $path = public_path('build/index.html');
    if (file_exists($path)) {
        return file_get_contents($path);
    }
    return view('welcome');
});
